server:
  port: {SERVER_PORT:8080}
spring:
  data:
    redis:
      host: ${TG_SCHEDULE_BOT_REDIS_HOST:localhost}
      port: ${TG_SCHEDULE_BOT_REDIS_PORT:8080}
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:memory}
logging:
  level:
    org.springframework: INFO
telegram-bot:
  config:
    name: ${TELEGRAM_BOT_NAME:name}
    token: ${TELEGRAM_BOT_TOKEN:token}
commands:
  poll:
    is-anonymous: ${TG_SCHEDULE_BOT_POLL_IS_ANONYMOUS:false}
    title: ${TG_SCHEDULE_BOT_POLL_TITLE:Кто будет сегодня играть?}