server:
  port: {SERVER_PORT:8080}

spring:
  application:
    public-prefix-path: ${TG_SCHEDULE_BOT_PUBLIC_URL_PREFIX:/api/tg-schedule-bot}
  data:
    redis:
      host: ${TG_SCHEDULE_BOT_REDIS_HOST:localhost}
      port: ${TG_SCHEDULE_BOT_REDIS_PORT:8080}
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:memory}

info:
  application:
    version: '@project.version@'

logging:
  level:
    org.springframework: INFO

telegram-bot:
  config:
    name: ${TELEGRAM_BOT_NAME:name}
    token: ${TELEGRAM_BOT_TOKEN:token}

commands:
  poll:
    beanName: ${POLL_COMMAND_BEAN_NAME:pollCommand}
    pattern: ${POLL_COMMAND_PATTERN:poll}
    chatTypes: ${POLL_COMMAND_CHAT_TYPES:private}
  info:
    beanName: ${INFO_COMMAND_BEAN_NAME:infoCommand}
    pattern: ${INFO_COMMAND_PATTERN:info}
    chatTypes: ${INFO_COMMAND_CHAT_TYPES:private,group,supergroup,channel}
  status:
    beanName: ${STATUS_COMMAND_BEAN_NAME:statusCommand}
    pattern: ${STATUS_COMMAND_PATTERN:status}
    chatTypes: ${STATUS_COMMAND_CHAT_TYPES:private,group,supergroup,channel}

feign:
  client:
    config:
      poll-service:
        url: ${POL_SERVICE_HOST:http://localhost:8080}
        api-base-url: ${POLL_SERVICE_PRIVATE_URL_PREFIX:/poll-service}